emotes:
  - ( ͡° ͜ʖ ͡°)
  - ¯\_(ツ)_/¯
  - ̿̿ ̿̿ ̿̿ ̿'̿'\̵͇̿̿\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
  - ▄︻̷̿┻̿═━一
  - ʕ•ᴥ•ʔ
  - ♪~ ᕕ(ᐛ)ᕗ
  - (ง ͠° ل͜ ͡°)ง
  - ༼ つ  ͡° ͜ʖ ͡° ༽つ
  - (╯°□°）╯︵ ┻━┻
  - ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
  - ┬──┬ ノ( ゜-゜ノ)
  - ヾ(⌐■_■)ノ♪
  - ~(˘▾˘~)
  - (~˘▾˘)~
  - \ (•◡•) /
  - ᕙ(⇀‸↼‶)ᕗ
  - ☜(˚▽˚)☞
  - ☜(⌒▽⌒)☞
  - ¬_¬
  - (✿´‿`)
  - ɿ(｡･ɜ･)ɾⓌⓗⓨ?
  - ɿ(｡･ɜ･)ɾⓌⓗⓐⓣ？
  - (ಠ ∩ಠ)
  - -`д´-